
services:
  nginx_local:
    image: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ${PWD}/nginx/nginx_local.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/www:/data/www
    command: >
      /bin/sh -c "chmod -R 755 /data/www &&
                  chmod -R a+r /data/www &&
                  nginx -g 'daemon off;'"

  flight:
    build: ./flight_info
    environment:
      - API_KEY=${API_KEY}
      - API_ENDPOINT=${API_ENDPOINT}
  
  chat:
    build: ./chatbot
    environment:
      - API_KEY=${API_KEY}
      - API_ENDPOINT=${API_ENDPOINT}

  ocr:
    build: ./ocr
    environment:
      - API_KEY=${API_KEY}
      - API_ENDPOINT=${API_ENDPOINT}

  healthcare:
    build: ./healthcare
    environment:
      - API_KEY=${API_KEY}
      - API_ENDPOINT=${API_ENDPOINT}