
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/www:/data/www
  
  flight:
    build: ./flight_info
    environment:
      - API_KEY=${API_KEY}
  
  chat:
    build: ./chatbot
    environment:
      - API_KEY=${API_KEY}

  ocr:
    build: ./ocr
    environment:
      - API_KEY=${API_KEY}

  healthcare:
    build: ./healthcare
    environment:
      - API_KEY=${API_KEY}