
services:
  nginx_local:
    image: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ${PWD}/nginx/nginx_local.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/www:/data/www

  flight:
    build: ./flight_info
    environment:
      - API_KEY=${API_KEY}
      - API_ENDPOINT=${BASE_URL}
  
  chat:
    build: ./chatbot
    environment:
      - API_KEY=${API_KEY}
      - API_ENDPOINT=${BASE_URL}

  ocr:
    build: ./ocr
    environment:
      - API_KEY=${API_KEY}
      - API_ENDPOINT=${BASE_URL}

  healthcare:
    build: ./healthcare
    environment:
      - API_KEY=${API_KEY}
      - API_ENDPOINT=${BASE_URL}